# Generated by Django 3.0.5 on 2023-09-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_blooddonationcertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.DeleteModel(
            name='BloodDonationCertificate',
        ),
    ]
